### PR TITLE
Change register_form hook to woocommerce_simple_registration_form #21

### PR DESCRIPTION
**Pull request by turtlepod**
register_form should not be loaded in register form. #21

### CODE REVIEW

**Comment by turtlepod** [comment]
@spencerfinnell do you remember why do we have `register_form` action here?
(woocommerce do not have this hook in their register form)

**Comment by spencerfinnell** [comment]
Nope. Looks like WooCommerce has been the same for a while: https://github.com/woocommerce/woocommerce/commit/35fc728090740b2a8b4490bc18e7eb7141b86471

Probably chose it because it's the core action: https://github.com/WordPress/WordPress/blob/2cde37040de1a34d61eb0930a4727f37595f05cd/wp-login.php#L751

Not sure if we should have both?

**Comment by turtlepod** [comment]
It's just make conditional harder, if we need to add in wp core vs add in wc differently, it will be added both. and make auth, etc feels wrong.

e.g adding recaptcha:
1. add in wp `register_form`
2. disable in wc form
3. it still show, because the hook is loaded there.

or:
1. enable in wp form
2. enable in wc form
3. result: we have 2 captcha loaded, if we disable in wc (because it's already added), it won't show in native wc register form,

**Comment by spencerfinnell** [comment]
Yeah we should remove it and only use the hooks found in https://github.com/woocommerce/woocommerce/blob/master/templates/myaccount/form-login.php

**Comment by spencerfinnell** [comment]
I'm not sure we need a custom one either. If something like Recaptcha is enabled in the Register form "for WooCommerce" I would imagine it would carry over to all WooCommerce-powered register forms.

**Comment by turtlepod** [comment]
I add it just "in case" we need to add only to this plugin form (The WC hook is still there).

Do you want to remove it? (I think it's fine)
https://github.com/Astoundify/woocommerce-simple-registration/blob/b62fbb0bb3b51370f159749203d8b863eef7cd14/templates/registration-form.php#L50

**Comment by spencerfinnell** [comment]
Yeah true we can keep it as long as nothing outputs there by default. When integrating things like Captcha we should use the hook that appears in WooCommerce core.

**Pull request merged**
